### ISSUE TITLE
node support

### ISSUE THREAD

**Issue by sakulstra** [0xsequence/sequence.js#118]
Hello,
i tried giving this a quick spin after reading https://twitter.com/Agusx1211/status/1373655105300537347 :rocket: 

It seems like there are issues though when using this inside node(ssr) :thinking:
For both InfuraProvider & JsonRPCProvider inside MulticallProvider i'm facing some issues `provider does not support network detection (operation="provider.detectNetwork", code=UNSUPPORTED_OPERATION, version=providers/5.0.24)` which I didn't face before. Is that a known issue? Cannot yet locate where exactly it has its origin as my build output is realively shitty - will alter this issue once i know more.

Using it like this:
```
const provider = new providers.MulticallProvider(
    new ethersProviders.InfuraProvider(
      "homestead",
      "xxx"
    ),
    { contract: "0xCa731e0f33Afbcfa9363d6F7449d1f5447d10C80" }
  );
```

**Comment by Agusx1211** [comment]
Thanks for the report!

It should be fixed on the latest version, 0.11.2

https://www.npmjs.com/package/@0xsequence/multicall
