### ISSUE TITLE
yarn add doesnt add sequence.js modules

### ISSUE THREAD

**Issue by sirpy** [0xsequence/sequence.js#216]
i'm using 
node v14.18.0
yarn 1.15.2
doing `yarn add 0x..` doesnt add the package in node_modules
it adds it to package.json
using `npm i` worked just fine
i've tried both the deployer and the utils packages

**Comment by pkieltyka** [comment]
@sirpy can you show exact yarn command you're trying?

you'll want to use..

`yarn add 0xsequence` if you're installing the main sequence library for wallet integration

however, if you want to use an individual package like the deployer, you'll need to use `yarn add @0xsequence/deployer`

**Comment by sirpy** [comment]
@pkieltyka i assure you its not some typo or mistake. as i've said it works fine with npm i.
i've tried both yarn add @0xsequence/deployer and yarn add @0xsequence/utils
