### ISSUE TITLE
Use another node service

### ISSUE THREAD

**Issue by suhailkakar** [0xsequence/sequence.js#287]
Hey!!
sequence.js is a great library but I was wondering will there be support for other node service like Chainstack. 

May I know if there is any specific reason why Infura is used a default node provider :)

**Comment by pkieltyka** [comment]
hi @suhailkakar yes you can use any node provider you'd like :)

if you'd like to show some sample code, we can show you how to configure your own provider. sequence.js is built on top of ethers.js
