### ISSUE TITLE
[@0xsequence/multicall] Update list of chains where the contract is deployed to

### ISSUE THREAD

**Issue by kasparkallas** [0xsequence/sequence.js#304]
These don't match:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/10894666/196705656-d7787c0d-0656-4030-8b4e-547810126ca2.png">
<img width="797" alt="image" src="https://user-images.githubusercontent.com/10894666/196705862-608405b9-b6c4-41b8-a14b-7878f2bca766.png">

**Comment by pkieltyka** [comment]
done in https://github.com/0xsequence/sequence.js/commit/a2385ea9e1d0e851039ef00fe05154c0e99584d4

thanks for the heads up and report :)
