### ISSUE TITLE
[@0xsequence/multicall] Consider making `ethers` a peerDependency

### ISSUE THREAD

**Issue by kasparkallas** [0xsequence/sequence.js#305]
I believe it's a good rule of thumb that when designing a library/SDK where you expose an interface/API of an internal dependency then you make it into a peer dependency. The reason is that when the consumer uses the same package (e.g. `ethers`) but of a slightly different version then weird TypeScript type mismatch errors can occur (especially for classes), even though they should be completely compatible.

For example here, if there's a new version of `ethers` out and the `Provider` had a non-related field added then they couldn't pass it in here:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/10894666/196707804-b47845cb-34b7-4d9e-9b34-98c2ec6ab752.png">

With `yarn`, using _[resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)_ in `package.json` would help remedy this as a workaround.

**Comment by pkieltyka** [comment]
done in https://github.com/0xsequence/sequence.js/pull/321

since 0.43.0 packages, ethers is now a peer dependency
