### ISSUE TITLE
[@0xsequence/multicall] Remove `@ethersproject/providers` dependency?

### ISSUE THREAD

**Issue by kasparkallas** [0xsequence/sequence.js#306]
It should be included under the `ethers` umbrella package that's already a dependency:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/10894666/196709426-32e10e4d-a6bf-45a6-92c4-67d47b761dad.png">

**Comment by pkieltyka** [comment]
done in https://github.com/0xsequence/sequence.js/pull/321

since 0.43.0 packages, ethers is now a peer dependency
