### ISSUE TITLE
Error: connectUnchecked is unsupported

### ISSUE THREAD

**Issue by desenvolvedorblockchain** [0xsequence/sequence.js#311]
Hello everyone,

We are trying to create a simple Mint page with Sequence + wagmi + infuraProvider using this project [https://github.com/0xsequence/demo-dapp-rainbowkit](url), and right now we are facing this error:

**mutation.mjs:134 Error: connectUnchecked is unsupported
    at Web3Signer.connectUnchecked (0xsequence-provider.esm.js:1402:1)
    at sendTransaction (wagmi-core.esm.js:1678:1)
    at async writeContract (wagmi-core.esm.js:1770:1)**

We have this code:

```
const provider = useProvider()
const { data: signer } = useSigner()

const { address } = useAccount();

let abiCoder = ethers.utils.defaultAbiCoder;
let dataEncoded = abiCoder.encode(["uint[]"], [[]]); 

const { config } = usePrepareContractWrite({
    address: '0x000', // Contract address
    abi: ERC_1155_ABI, // basic ERC1155 contract
    functionName: 'mint',
    args: [
        address, // address to mint
        0, // ids
        1, // amount
        dataEncoded,
      ],
    overrides: {
        value: ethers.utils.parseEther('0.01'),
    },
})
const { data, error, isError, write } = useContractWrite(config);
```
  
  and then, in the button, we used:
  
```
<Button disabled={!write} onClick={() => write?.()}>
      Mint NFT
</Button>
```
  to call the write from useContractWrite

We searched all over the internet to find out what this error: "connectUnchecked is unsupported" could be, but we didn't find anything.

Thank you!

**Comment by pkieltyka** [comment]
thanks for the report -- we'll implement this method to unblock you :) will keep you posted

**Comment by pkieltyka** [comment]
@desenvolvedorblockchain Please try sequence version 0.43.2 and let us know how it goes :) this should now be resolved
