### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'listenerCount')

### ISSUE THREAD

**Issue by shuhuiluo** [0xsequence/sequence.js#402]
Since version `^1.0.0`, `MulticallProvider` stopped working. I tried to instantiate it with `InfuraProvider` and encountered the following error:
```
TypeError: Cannot read properties of undefined (reading 'listenerCount')
  at new MulticallProvider (node_modules\@0xsequence\multicall\dist\0xsequence-multicall.cjs.dev.js:321:40)
```
On line 321 of 0xsequence-multicall.cjs.dev.js, there is
```
    this.listenerCount = this.provider.listenerCount;
```
which supercedes
```
    this.provider = _provider;
```
on line 348.

**Comment by icyage** [comment]
no update for this?

**Comment by shuhuiluo** [comment]
Error goes away at least for `1.2.9`.
