### ISSUE TITLE
Current network is not respected on fiat on-ramp

### ISSUE THREAD

**Issue by SebastianJ21** [0xsequence/sequence.js#422]
**Description:**
No matter the `sequence` network setting, the network in _wallet/add-funds_ flow  is immutably set to Polygon. This is very confusing for users buying funds, because they have to notice and manually change the network.

**Expected behavior:**
Either a specific setting for the network in the `OpenWalletIntent`, or use the currently used network (or at least the default)

**Example:**
```
const handleFundWallet = () => {
    const path = 'wallet/add-funds'
    const intent: OpenWalletIntent = {
      type: 'openWithOptions',
      options: {
        app: 'My App',
        settings: {
          defaultFundingCurrency: 'eth',
          includedPaymentProviders: ['moonpay', 'ramp'],
        },
      },
    }
    sequenceWallet.openWallet(path, intent) // sequenceWallet = sequence.getWallet() 
  }
```
This code snippet will always use Polygon as its underlying network, i.e. the preset `ETH` will be `ETH (POLYGON)`.

**Comment by PhABC** [comment]
Thanks for the report @SebastianJ21 !
