### ISSUE TITLE
Upgrade to ethers v6

### ISSUE THREAD

**Issue by haydenfowler** [0xsequence/sequence.js#441]
Hi team, 

`ethers` v6 was released approximately 9 months ago, but the `@0xsequence` package specifies `ethers >=5.5 < 6` as a peer dependency ([@0xsequence/package.json](https://github.com/0xsequence/sequence.js/blob/master/packages/0xsequence/package.json#L50)).

Are there any plans to migrate to ethers v6?

**Comment by pkieltyka** [comment]
most definitely! will be soon

**Comment by haydenfowler** [comment]
> most definitely! will be soon

Thanks for the response @pkieltyka! 
Do you have a rough estimate for when v6 will be supported?

**Comment by KholdStare** [comment]
I would vote to remove usage of ethers entirely, and move to `viem` instead . It is used by sequence-kit and majority of other frontend libraries. Ethers is bloated, and because sequence-kit also uses viem, there's double the bloat, so the efficiency of using a smaller/faster package like `viem` is squandered.

**Comment by baltarifcan** [comment]
are there any updates on this?

**Comment by pkieltyka** [comment]
we are very very close to shipping this :) within 2 weeks will be in prod

**Comment by jxom** [comment]
Would be good to consider compatibility with Viem. Most at-scale (and small-scale) projects are starting to utilize it now.

![CleanShot 2024-08-27 at 17 29 09@2x](https://github.com/user-attachments/assets/f472d86a-4ecc-4864-8d70-89b7fee74667)

**Comment by pkieltyka** [comment]
hey @jxom for sure, we're big fans of viem and we have planned work to update sequence.js for further refactoring to enhance the library and make it easier to use other libs under-the-hood such as viem (without ethers), if a developer chooses. 

but also, right now, viem is fully compatible with sequence.js and many developers do that, it just works along-side ethers.js.

**Comment by pkieltyka** [comment]
sequence v2.0.x is now on ethers v6 as of a few weeks ago. Closing this ticket.
